# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 3.3

# Exclude the template files from standardrb checks
ignore:
  - 'lib/generators/**/templates/**'
